### ISSUE TITLE
Requirements parsing crashes in certain cases when a requirement indsicated in an implementsReq statement does not have a matching req statement

### ISSUE THREAD

**Issue by TimLethbridge** [umple-ucosp/umple#2051]
This is a sub-issue of #1865 which is the main issue for the requirements feature.

The following code causes a crash during analysis following parsing. It seems to be related to when there is an implementsReq that does not match a req
```
req RT3 {
}

class X {
  implementsReq RT4;
  a;
}
```

It also occurs if there are no req statements at all (this should be another test). Or if a matching req statement is in a mixset that is not activated with a use statement.,

**Comment by TimLethbridge** [comment]
The crash for this is as below. We identified that the code tagged parser is from UmpleParser/ParseUtilities_Code.ump

```
Exception java.lang.NullPointerException (Cannot invoke 'java.lang.CharSequence.length()' because 'this.text' is null) in
 at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
 at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
 at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
 at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
 at java.base/java.util.regex.Pattern.matches(Pattern.java:1175)
 at cruise.umple.parser.Token.isValidIdentifier(Token.java:290)
   => parser:23
 at cruise.umple.parser.Token.isValidIdentifier(Token.java:298)
   => parser:30
 at cruise.umple.compiler.UmpleInternalParser.analyzeAttribute(UmpleInternalParser.java:6687)
   => UmpleInternalParser_CodeClass.ump:4725
 at cruise.umple.compiler.UmpleInternalParser.analyzeImplementReq(UmpleInternalParser.java:2183)
   => UmpleInternalParser_CodeClass.ump:251
 at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:2330)
   => UmpleInternalParser_CodeClass.ump:396
 at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:1520)
   => UmpleInternalParser_Code.ump:270
 at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:1462)
   => UmpleInternalParser_Code.ump:204
 at cruise.umple.compiler.UmpleInternalParser.analyzeClass(UmpleInternalParser.java:3383)
   => UmpleInternalParser_CodeClass.ump:1450
 at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:2095)
   => UmpleInternalParser_CodeClass.ump:163
 at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:1485)
   => UmpleInternalParser_Code.ump:225
 at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:1431)
   => UmpleInternalParser_Code.ump:176
 at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:1360)
   => UmpleInternalParser_Code.ump:106
 at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1757)
   => Umple_Code.ump:208
 at cruise.umple.UmpleConsoleMain.runConsole(UmpleConsoleMain.java:165)
   => Main_Code.ump:295
 at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:285)
   => Main_Code.ump:413

```

**Comment by TimLethbridge** [comment]
It was discovered that analyzeImplementReq a call was being made to analyzeAttribute when instead it should have been reporting an error
